// Generated by https://quicktype.io

export interface Service {
    services: ServiceElement[];
}

export interface ServiceElement {
    id:           number;
    name:         string;
    description:  string;
    price:        number;
    subservices?: ServiceElement[];
}
