// Generated by https://quicktype.io

export interface Service {
    services: ServiceElement[];
}

export interface ServiceElement {
    id:           number;
    name:         string;
    description:  string;
    price:        number;
    initialQuantity: number;
    subservices?: ServiceElement[];
}

export interface SelectedService {
    id: number;
    price: number;
    subservices?: {
        id: number;
        quantity: number;
        price: number;
    }[];
}
